name: Deploy the WOO Page to GitHub Pages

env: # Change these to your preferences any image url can also be a base encoded image
  GITHUB_PAGES_BRANCH: gh-pages

  # options: "true" | "false"
  USE_GITHUB_REPOSITORY_NAME_AS_PATH_PREFIX: "true"

  GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
  API_BASE_URL: "https://api.gateway.commonground.nu/api"
  NL_DESIGN_THEME_CLASSNAME: "gouda-theme"
  DEV_ENVIRONMENT: "true"
  SHOW_CATEGORY: "true"
  SHOW_ORGANIZATION: "false"
  DATE_FULL_MONTH: "true"
  FAVICON_URL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAC8ElEQVRYhc2Xz0tUURTHP0dMosT3CL2EDBEiLmyYogYpEZEyiaht0KraBhKB0aJFixbRH5DQpmhRixZRi37Qj41ZmYQFiUiJuJCIG5jPhYhGp8W8dObNfW9mcEIPzGLuOef7/XLnzveeC5s1rGd2JOTqrW9qq4FVE9OQAV5aL4ZE2A3csn6Tsz+CtRN4bz3T4IYqLO5BOInSi0gG1QcIsyjXTGDnV+t8kwb5guqgiPY3zf/84yBOI5xDySLSjeoLhHGUmyaw03E7MI5yFpFMTp6cQknlkxfKl/OqcuOX57t24ivKCUS6w9o+lC5gJr8o2rgUfvLDTb4mYmCFuqvFCf0NLEQWF7awXLAQFdCJMIxqTqXqENBgPeMni2DAsZhBmEZ1PMQaQ5hboa6lsNUR1jNdwF1gjwlsdEfWzsBq6KKZt9tjsFqAt8BeE1gbzTtPsQnsMHDERV5phAfukIs8VkDYOLNe8nKwSv6P/3dsXgHWM83VIknCirPiDuC19UxdFch3AR+sZxpd+dpIcS/CaZQuRNpQfWx9M4tyKdYN44h9kwEuoGQQSYVYkyjXTWCn/tVFd2AU5TgibQCIHEOprZQcAGUivAeyIVYnSquITueXRQXUONbKvnYdUYSvmlywH+ERqpMAqD4FFktasTvaEd6hOpr7qkMIEyBlWXEWuAMcMIFdLspXZsUp4E2INRfNx1nxR+Coi7zSMIGdJWfFReSxAsLGH+slLwdr8zrhhgsIHawqkYQVZ8Wd5KbirVUgbyU3FTtH86gV9yGcQTmISAuqT6xvvqP0V2zFnskiXAytuBnVZ9Y3UyhX8ueD6A6MoPQgoVmIHEZZKkmuDDoWP6OkEUmHWB0ojdHhxGW70RuwPplcB0X0cnFCaoDoT7jNeoWPmaiADCL38ybZhwg23or1NjEPE6AdkeeojoRYrxAZAyl9uK1n9lnPfIp7mlnfpK1n7sU+3QqxUtYz3+KeZkmNzgEizNVbv/xhJQlrw+Mv2nwzfANTJkAAAAAASUVORK5CYII="
  ORGANISATION_NAME: "Gemeente Gouda"
  JUMBOTRON_IMAGE_URL: https://raw.githubusercontent.com/ConductionNL/woo-website-gouda/main/images/jumbotron.jpg
  FOOTER_LOGO_URL: "true"
  FOOTER_LOGO_HREF: "https://www.gouda.nl/"
  FOOTER_CONTENT: "https://raw.githubusercontent.com/ConductionNL/${{github.event.repository.name}}/main/FooterContent.json"
  FOOTER_CONTENT_HEADER: "heading-4"
  OIDN_NUMBER: "00000001001997956000"
  ENV_VARS_SET: "true"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the WOO Website Template Code
        uses: actions/checkout@v2
        with:
          repository: ConductionNL/woo-website-template
          ref: development

      # With special thanxs to https://github.com/SpicyPizza/create-envfile
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_GITHUB_REPOSITORY_NAME: ${{ env.GITHUB_REPOSITORY_NAME }}
          envkey_USE_GITHUB_REPOSITORY_NAME_AS_PATH_PREFIX: ${{ env.USE_GITHUB_REPOSITORY_NAME_AS_PATH_PREFIX }}
          envkey_GATSBY_API_BASE_URL: ${{ env.API_BASE_URL }}
          envkey_GATSBY_NL_DESIGN_THEME_CLASSNAME: ${{ env.NL_DESIGN_THEME_CLASSNAME }}
          envkey_GATSBY_DEV_ENVIRONMENT: ${{ env.DEV_ENVIRONMENT }}
          envkey_GATSBY_SHOW_CATEGORY: ${{ env.SHOW_CATEGORY }}
          envkey_GATSBY_SHOW_ORGANIZATION: ${{ env.SHOW_ORGANIZATION }}
          envkey_GATSBY_DATE_FULL_MONTH: ${{ env.DATE_FULL_MONTH }}
          envkey_GATSBY_FAVICON_URL: ${{ env.FAVICON_URL }}
          envkey_GATSBY_ORGANISATION_NAME: ${{ env.ORGANISATION_NAME }}
          envkey_GATSBY_JUMBOTRON_IMAGE_URL: ${{ env.JUMBOTRON_IMAGE_URL }}
          envkey_GATSBY_FOOTER_LOGO_URL: ${{ env.FOOTER_LOGO_URL }}
          envkey_GATSBY_FOOTER_LOGO_HREF: ${{ env.FOOTER_LOGO_HREF }}
          envkey_GATSBY_FOOTER_CONTENT: ${{ env.FOOTER_CONTENT }}
          envkey_GATSBY_FOOTER_CONTENT_HEADER: ${{ env.FOOTER_CONTENT_HEADER }}
          envkey_GATSBY_OIDN_NUMBER: ${{ env.OIDN_NUMBER }}
          envkey_GATSBY_ENV_VARS_SET: ${{ env.ENV_VARS_SET }}
          directory: pwa/static
          file_name: .env.production
          fail_on_empty: true
          sort_keys: false

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: cd pwa && npm install

      - name: Install parcel/watcher
        run: cd pwa && npm install @parcel/watcher

      - name: Remove old Gatsby cache
        run: rm -rf pwa/.cache

      - name: Build application
        run: cd pwa && npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: ${{ env.GITHUB_PAGES_BRANCH }}
          folder: pwa/public
